[deploy]
bucket = 'cfn-artifacts-lhviet204'
region = 'us-east-1'
stack_name = 'CrdSyncRole'

[parameters]
GitHubOrg = 'lhviet204'
RepositoryName = 'aws-bootcamp-cruddur-2023'
OIDCProviderArn = '//TODO'