version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io/"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      OTEL_SERVICE_NAME: "cruddur-be-flask"
      AWS_XRAY_URL: "*4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}*"
      AWS_XRAY_DAEMON_ADDRESS: "xray-daemon:2000"
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"      
      ROLLBAR_ACCESS_TOKEN: "${ROLLBAR_ACCESS_TOKEN}"  
    build: ./backend-flask
    ports: 
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    healthcheck:
      test: ["CMD", "curl", "-f", "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}/api/activities/home"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      REACT_APP_OTLP_COLLECTOR_URL: "https://4318-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}/v1/traces"    
    build: ./frontend-react-js
    ports: 
      - "3000:3000"
    volumes: 
      - ./frontend-react-js:/frontend-react-js
  # db:
  #   image: postgres:13-alpine
  #   restart: always
  #   environment:
  #   - POSTGRES_USER=postgres
  #   - POSTGRES_PASSWORD=password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db:/var/lib/postgresql/data
  # Collector
  otel-collector:
    environment:
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      HONEYCOMB_API_KEY: "${HONEYCOMB_API_KEY}"
    image: otel/opentelemetry-collector
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./components/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4318:4318 # OTLP http collector
  # xray-daemon:
  #    image: "amazon/aws-xray-daemon"
  #    environment:
  #      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  #      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  #      AWS_REGION: "us-east-1"
  #    command:
  #      - "xray -o -b xray-daemon:2000"
  #    ports:
  #      - 2000:2000

volumes:
  db:
    driver: local

networks:
  internal-network:
    driver: bridge
    name: cruddur

