[deploy]
bucket = 'cfn-artifacts-lhviet204'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'lhviet204/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-artifacts-lhviet204"
BuildSpec = 'backend-flask/buildspec.yml'